# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-30 16:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='moveevent',
            name='timestapm',
            field=models.DateTimeField(default=datetime.datetime(2016, 1, 30, 17, 47, 19, 215379)),
        ),
    ]
