# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-23 17:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moveevent',
            name='timestamp',
            field=models.FloatField(default=0),
        ),
    ]
